### PR TITLE
Support Python 3

### PR DESCRIPTION
**Pull request by anhdat**
Hi @rsgalloway, I'm writting a CLI app to read Instapaper offline on Python 3.

What I did was adding Python 3 compatible code with [futurize](http://python-future.org/futurize.html#futurize-py2-to-py2-3), the repo should run on Python 2.7 just fine.

Hope this get merged. Ping me if you need any modification. Thanks.

### CODE REVIEW

**Comment by rsgalloway** [comment]
Looks fine. Did you test it with Python 2.5 and 2.6 by any chance? (I know 2.5 is pretty old but I guess it's still out there)

**Comment by anhdat** [comment]
hi @rsgalloway, I've just setup tox, wrote some tests and test on py27 and py35. Got this:

```
  py27: commands succeeded
  py35: commands succeeded
  congratulations :)
```

**Comment by anhdat** [comment]
@rsgalloway any update?

**Comment by rsgalloway** [comment]
Thanks. I'll merge and dist this tonight. Thanks for your patience!

**Comment by anhdat** [comment]
Thanks @rsgalloway 👍

**Pull request merged**
